name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Ou a branch que deseja usar

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: localdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Build with Maven (skip tests optional)
        run: ./mvnw clean package -DskipTests=true

      - name: Run tests
        run: ./mvnw test

      - name: Build Docker image
        run: docker build -t cadpessoas:v1 .

      # Exemplo de deploy simples (depende do seu ambiente)
      # - name: Push Docker Image to Docker Hub (opcional)
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker tag cadpessoas:v1 yourdockerhubuser/cadpessoas:v1
      #     docker push yourdockerhubuser/cadpessoas:v1

      # - name: Deploy on server (exemplo com SSH)
      #   uses: appleboy/ssh-action@v0.1.5
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull yourdockerhubuser/cadpessoas:v1
      #       docker stop cadpessoas || true
      #       docker rm cadpessoas || true
      #       docker run -d -p 8080:8080 --name cadpessoas yourdockerhubuser/cadpessoas:v1
