name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: localdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: maven

      - name: Permitir execução do mvnw
        run: chmod +x mvnw

      - name: Esperar PostgreSQL ficar disponível
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Build com Maven (sem testes)
        run: ./mvnw clean package -DskipTests=true

      - name: Testes com Maven
        run: ./mvnw test

      - name: Build Docker image
        run: docker build -t cadpessoas:v1 .
